config/routes.rb
Rails.application.routes.draw do

  devise_for :users


  root 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user


  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/post_image.rb
class PostImage < ApplicationRecord
  

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :email, presence: true
  validates :introduction, length: {maximum: 50}



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!,except: [:top, :about]


  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :correct_user, only: [:edit, :update]


  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
      if @book.save
        flash[:notice] = "You have created book successfully."
        redirect_to book_path(@book.id)
      else
        @books = Book.all
        render :index
      end
  end


  def show
    @newbook = Book.new 
    @books = Book.all
    @book = Book.find(params[:id])
    @user = @book.user
    
  end

  def edit
    @book = Book.find(params[:id])

    @user = User.find_by(id: @book.user_id)
    if @user == current_user
        render :edit
    else
        redirect_to :top
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top

  end

  def about

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render :edit
    else
        redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path
    else
      render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path

  end

  private

  def user_params
  params.require(:user).permit(:name, :introduction, :profile_image)
  end
  def correct_user
    @user = User.find(params[:id])

    redirect_to(user_path(current_user.id)) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_userinfo.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


    <p id="notice"></p>
    <div class="container px-5 px-sm">
      <div class="row">
        <div class="col-md-3">

          <h2>User info</h2><br />
          <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "images/no_image.jpg" %><br>


          <taable class="table">
            <tbody>
              <tr></tr>
            <tr>
              <th>name</th>
              <th><%= user.name %></th><br>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
            </tbody>
            </taable>

<%= link_to edit_user_path(user), class: "btn btn-primary form-control" do %>
  <i class="fas fa-user-cog"></i>

<% end %>




              <h2 class="mt-3">New book</h2>
                <%= form_with model: book, local:true do |f| %>


                <div class="form-group">
                <label for="book_title">Title</label><br />
                  <%= f.text_field :title %></div><br />

                <div class="form-group">
                <label for="book_title">Opinion</label><br />
                  <%= f.text_area :body %>
                </div>
                  <%= f.submit 'Create Book' %>

               <% end %>
        </div>

app/views/books/edit.html.erb
 <body>


   <main>
    <% if @book.errors.any? %>
     <div id="error_explanation">
      <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
      </ul>
      </div>
    <% end %>
   <p id="notice"></p>
   <div class="container">
     <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
    <%= form_with model:@book, local: true do |f| %>

    <div class="form-group">
      <label for="book_title">Title</label><br>
      <%= f.text_field :title %>
    </div>

      <div class="form-group">
        <label for="book_body">Opinion</label><br>
          <%= f.text_area :body %>
      </div>
      <%= f.submit 'Update Book' %>

    <p><%= link_to 'Show' , book_path(@book) %> | <%= link_to 'Back' , "/books" %></p>
    <% end %>
  </div>
  </main>

</body>

app/views/books/index.html.erb
<main>

<%= render 'books/userinfo', book: @book, user: @user %>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
    <table class="table taable-striped">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
         </tr>
      </thead>

        <% @books.each do |book| %>

        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "images//no_image.jpg" %>
            <% end %>
          </tb>

          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>

        </table>

</div>
</main>

app/views/books/new.html.erb
<h1>New Book</h1>

    <%= form_with model: @book, local:true do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %><br>

    <%= f.submit 'Create Book' %>

    <% end %>

app/views/books/show.html.erb
<main>

<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<%= render 'books/userinfo', book: @newbook, user: @user %>

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
    <table class="table">
      <thead>


        <tr>
          <td>
            <%= link_to user_path(@user.id) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "images/no_image.jpg" %>
            <% end %><br />
            <%= link_to @user.name, user_path(@book.user_id) %>
          </tb>

          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>


          <% if current_user.id == @user.id %>
            <td><%= link_to 'Edit' , edit_book_path(@book.id), class:"btn-sm btn-success" %></td>
            <td><%= link_to "Destroy",book_path(@book), class:"btn-sm btn-danger", method: :delete,data: { confirm: '本当に消しますか?' } %></td>
          <% end %>

        </tr>
      </thead>
</table>

</div>
</main>

app/views/homes/about.html.erb
<main>

  <p id="notice"></p>
  <div class="row">
    <h1 class="px-3 mx-auto">
      welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !</h1>

    </div>
  </div>

</main>

app/views/homes/top.html.erb
<main>
  
  <p id="notice"></p>
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      
      
      
      
      <div class="btn-wrapper col-10 mx-auto">
        
        <div class="row">
           <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
        
      </div>
    </div>
  </div>
  
</main>

app/views/layouts/_flash.html.erb
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

  <%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <header>


     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">


            <% if user_signed_in? %>


            <li><%= link_to "Home", user_path(current_user.id) , class:"fas fa-home nav-link text-light" %></li>

            <li><%= link_to "Users", users_path, class:"fas fa-users nav-link text-light" %></li>

            <li><%= link_to "Books", books_path, class:"fas fa-book-open nav-link text-light" %></li>

            <li><%= link_to "Log out", destroy_user_session_path, class:"fas fa-sign-out-alt nav-link text-light", method: :delete %></li>

            <% else %>


            <li><a class="fas fa-home nav-link text-light" href="/">Home</a></li>
            <li><a class="fas fa-link nav-link text-light" href="/home/about">About</a></li>

            <li><%= link_to "Sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %></li>

            <li><%= link_to "Log in", user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %></li>

            <% end %>



           </ul>
         </div>
       </div>
     </nav>

    </header>


    <main>


  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>


 

    </main>


    <%= yield %>


    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h2>User Info</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%><br />

  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "images/no_image.jpg" %><br />
  <label for="inputImage">Image</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>


  <br /><label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, class: 'form-control' %><br />


<br /><%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<main>

<%= render 'books/userinfo', book: @book, user: @user %>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3" /th>
        </tr>
      </thead>


      <tbody>

        <% @users.each do |user| %>
        <div><tr>

          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "images/no_image.jpg" %></td>
          <td><%= user.name %></td>

          <td><%= link_to "Show", user %></td>

        </tr></div>

        <% end %>
        </tbody>
        </table>


</div>
</div>



        </div>
      </div>
    </div>
</main>

app/views/users/show.html.erb
<main>


<%= render 'books/userinfo', book: @book, user: @user %>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
         </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "images/no_image.jpg" %>
            <% end %>
          </tb>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body%></td>

        </tr>
        <% end %>

      </tbody>

    </table>
    </div>
</div>



        </div>
      </div>
    </div>


</main>